services:
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd
      MYSQL_USER: junk_user
      MYSQL_PASSWORD: junk_user_password
      MYSQL_DATABASE: junkdrawer
  spring-boot-app:
      build:
        context: .
      ports:
        - "8080:8080"
      depends_on:
        - mysql
      environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/junkdrawer
        SPRING_DATASOURCE_USERNAME: junk_user
        SPRING_DATASOURCE_PASSWORD: junk_user_password
        SPRING_PROFILES_ACTIVE: dev